export type {
  Conflict,
  ConflictCategory,
  ConflictEntry,
  ConflictEvent,
  Milestone,
  MilestoneCategory,
  MilestoneCategoryGroup,
  OccupationDomain,
  Period,
  Person,
  PointInTime,
  Region,
  YearMonth,
} from '@o-tempora/shared-types';
export {
  AVG_CHAR_WIDTH_PX,
  CONFLICT_CATEGORIES,
  estimateLabelWidthPx,
  MILESTONE_CATEGORIES,
  MILESTONE_CATEGORY_GROUPS,
  MILESTONE_CATEGORY_TO_GROUP,
  OCCUPATION_DOMAINS,
  POINT_LABEL_OFFSET_PX,
  POINT_RADIUS,
  REFERENCE_SCALE_PIXELS_PER_YEAR,
  REGIONS,
  wrapLabelLines,
  wrapMarkLabelLines,
  yearMonthToFractionalYear,
} from '@o-tempora/shared-types';
